# Generated by Django 2.0.3 on 2018-03-20 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20180320_2315'),
        ('post', '0003_auto_20180320_2315'),
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='to_post',
        ),
        migrations.AddField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='comment.Comment', verbose_name='Liked comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='post.Post', verbose_name='Liked post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
    ]
